apiVersion: v1
kind: Namespace
metadata:
  name: bookstore

---
apiVersion: v1
kind: Namespace
metadata:
  name: bookbuyer
 
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookthief
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookwarehouse 
